# Generated by Django 3.1.4 on 2021-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
