# Generated by Django 3.1.2 on 2021-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=180)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('uptime', models.FloatField(blank=True, max_length=255, null=True)),
                ('sessions', models.CharField(blank=True, max_length=255, null=True)),
                ('processes', models.CharField(blank=True, max_length=255, null=True)),
                ('processes_array', models.TextField(blank=True, null=True)),
                ('file_handles', models.CharField(blank=True, max_length=255, null=True)),
                ('file_handles_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('os_kernel', models.CharField(blank=True, max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, max_length=255, null=True)),
                ('os_arch', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_cores', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_freq', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_total', models.FloatField(default=0, max_length=255, null=True)),
                ('ram_usage', models.FloatField(default=0, max_length=255, null=True)),
                ('swap_total', models.FloatField(default=0, max_length=255, null=True)),
                ('swap_usage', models.FloatField(default=0, max_length=255, null=True)),
                ('disk_array', models.TextField(blank=True, null=True)),
                ('disk_total', models.FloatField(default=0, max_length=255, null=True)),
                ('disk_usage', models.FloatField(default=0, max_length=255, null=True)),
                ('connections', models.CharField(blank=True, max_length=255, null=True)),
                ('nic', models.CharField(blank=True, max_length=255, null=True)),
                ('ipv_4', models.CharField(blank=True, max_length=255, null=True)),
                ('ipv_6', models.CharField(blank=True, max_length=255, null=True)),
                ('rx', models.FloatField(default=0, max_length=255, null=True)),
                ('tx', models.FloatField(default=0, max_length=255, null=True)),
                ('rx_gap', models.FloatField(default=0, max_length=255, null=True)),
                ('tx_gap', models.FloatField(default=0, max_length=255, null=True)),
                ('loads', models.CharField(default=0, max_length=255, null=True)),
                ('load_cpu', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('load_io', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('load_system', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('ping_eu', models.FloatField(default=0, max_length=255, null=True)),
                ('ping_us', models.FloatField(default=0, max_length=255, null=True)),
                ('ping_as', models.FloatField(default=0, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_notice', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('notice_load', models.IntegerField(default=80)),
                ('notice_ram', models.IntegerField(default=80)),
                ('notice_disk', models.IntegerField(default=80)),
                ('have_notice', models.BooleanField(default=False)),
                ('last_notice_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'hosts',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
    ]
