# Generated by Django 3.1.4 on 2021-01-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20210101_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hosts',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hosts',
            name='notice_disk',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='hosts',
            name='notice_load',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='hosts',
            name='notice_ram',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='disk_total',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='disk_usage',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='load_cpu',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='load_io',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='loads',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ping_as',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ping_eu',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ping_us',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ram_total',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ram_usage',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='rx',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='rx_gap',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='swap_total',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='swap_usage',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='tx',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='tx_gap',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='uptime',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
