# Generated by Django 3.1.4 on 2021-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20210101_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='load_system',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='load_cpu',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='load_io',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
