# Generated by Django 3.1.4 on 2021-01-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20210102_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'default_permissions': (), 'ordering': ['-id']},
        ),
    ]
